# Postgres credential: generated by Terraform, never written to any committed file.
# Previously a hardcoded plaintext "dtx_dev_pw" directly in ecs.tf's container
# definitions (both the postgres task itself and dispatch-service's PG_URL) - visible
# in git history. Replaced with a Terraform-generated random password stored only in
# SSM Parameter Store as a SecureString, referenced by both task definitions via a
# `secrets` block (ECS resolves it at container start; the container still just sees a
# plain POSTGRES_PASSWORD/PG_URL env var, so no application code changes needed).
#
# random_password's `result` is stored in terraform.tfstate, which is already
# gitignored (never committed) - this only removes the password from version-controlled
# source, it does not add encryption-at-rest for the local state file itself.
#
# SSM SecureString here uses the AWS-managed "alias/aws/ssm" KMS key (the default when
# no key_id is given) - no custom KMS key/IAM policy to provision, matching the "no
# iam:CreateRole/PutRolePolicy" constraint this Academy account already has. Whether the
# shared LabRole (execution role on every task) actually has ssm:GetParameters +
# kms:Decrypt has not been tested before this change - unverified risk, same class as
# the ecs.application-autoscaling service-linked role check in Week 8c-iii.

resource "random_password" "postgres" {
  length  = 24
  special = false # keeps the value safe to embed directly in a postgresql:// URL
}

resource "aws_ssm_parameter" "postgres_password" {
  name  = "/${var.project_name}/postgres/password"
  type  = "SecureString"
  value = random_password.postgres.result

  tags = {
    Name = "${var.project_name}-postgres-password"
  }
}

resource "aws_ssm_parameter" "postgres_url" {
  name  = "/${var.project_name}/postgres/url"
  type  = "SecureString"
  value = "postgresql://dtx:${random_password.postgres.result}@${aws_lb.internal.dns_name}:5432/driverless_taxi"

  tags = {
    Name = "${var.project_name}-postgres-url"
  }
}
